services:

  backend:
    build: ./backend
    ports:
      - 8000:8000


  frontend:
    build: ./frontend 
    ports:
      - 5173:5173  


  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro


  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    
    
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
    - mongo_data:/data/db

    

volumes:
  minio_data:
  mongo_data:
