services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - user_service
            - post_service
            - notification_service

    minio:
        image: minio/minio
        command: server /data --console-address ":9001"
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - minio_data:/data
        # environment:
        #     MINIO_ROOT_USER: ${MINIO_ROOT_USER}
        #     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    mongodb_user:
        image: mongo:latest
        ports:
            - 27018:27017
        volumes:
            - mongo_user_data:/data/db

    mongodb_post:
        image: mongo:latest
        ports:
            - 27019:27017
        volumes:
            - mongo_post_data:/data/db
    
    mongodb_notification:
        image: mongo:latest
        ports:
            - 27020:27017
        volumes:
            - mongo_notification_data:/data/db

    frontend:
        build: ./frontend
        ports:
            - 5173:5173

    user_service:
        build: ./backend/user
        ports:
            - 8001:8001
        depends_on:
            - mongodb_user

    post_service:
        build: ./backend/post
        ports:
            - 8002:8002
        depends_on:
            - mongodb_post

    notification_service:
        build: ./backend/notification
        ports:
            - 8003:8003
        depends_on:
            - mongodb_notification
            - post_service
volumes:
    minio_data:
    mongo_user_data:
    mongo_post_data:
    mongo_notification_data:
